name: android_build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup Android SDK 34
        uses: amyu/setup-android@v4
        with:
          sdk-version: 34
          build-tools-version: 34.0.0
          ndk-version: 25.2.9519653
      - name: Install LSPosed latest
        run: |
          LATEST_LSP_URL=$(curl -s https://api.github.com/repos/LSPosed/LSPosed/releases/latest | grep "browser_download_url.*zip" | cut -d '"' -f 4)
          wget $LATEST_LSP_URL -O lsposed.zip
          unzip lsposed.zip -d $ANDROID_HOME/lsposed
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew assembleDebug -Psdk_version=34
        env:
          ANDROID_HOME: ${{ env.ANDROID_HOME }}
      - name: Cache Android SDK
        uses: actions/cache@v3
        with:
          path: |
            ~/.android/cache
            $ANDROID_HOME
          key: android-sdk-34-${{ runner.os }}
